import logging
from typing import Dict, Any, Optional
import json

logger = logging.getLogger(__name__)

class TaskHandler:
    def __init__(self, llm, task_stack_manager, task_planner, memory_manager):
        self.llm = llm
        self.task_stack_manager = task_stack_manager
        self.task_planner = task_planner
        self.memory_manager = memory_manager

    async def handle_stuck_task(self, request: Dict[str, Any]) -> Dict[str, Any]:
        """Handle internal stuck-task requests from the mid-level brain."""

        active_task = self.task_stack_manager.get_active_task()
        if not active_task:
            logger.warning("Received stuck-task request but the task stack is empty")
            return {
                'decision': 'no_change',
                'explanation': 'No active task to modify.',
                'guidance': 'Wait for a new task from the high-level brain.'
            }

        task_source = active_task.get('source', 'internal')
        player_name = active_task.get('player_name')
        step_index = request.get('current_step_index', active_task.get('current_step_index', 0))
        failures = request.get('failures', [])
        suggestion = request.get('suggestion', '')
        reason = request.get('reason', '')

        steps = active_task.get('steps', [])
        failed_step = steps[step_index] if 0 <= step_index < len(steps) else {}

        recent_memory_text = self._extract_recent_memories_text(50)
        stack_summary = self.task_stack_manager.generate_task_stack_summary()
        current_plan_text = self.task_planner.format_task_plan_for_prompt(active_task)

        player_context = ""
        if player_name:
            player_data = self.memory_manager.get_player_data(player_name) or {}
            relationship = player_data.get('relationship', 'neutral')
            trust_level = player_data.get('trust_level', 0.5)
            personality = ", ".join(player_data.get('personality', [])[-3:]) or 'unknown'
            preferences = ", ".join(player_data.get('preferences', [])[-3:]) or 'unknown'
            player_context = (
                f"Player: {player_name}\n"
                f"Relationship: {relationship}\n"
                f"Trust level: {trust_level:.2f}\n"
                f"Traits: {personality}\n"
                f"Preferences: {preferences}\n"
            )

        prompt = f"""
You are the strategic planner for a Minecraft agent. Your role is to make high-level decisions to help the agent achieve its goals. The mid-level executor, which follows your plans, is currently stuck on a task.

BACKGROUND:
- The **Task Stack** is a Last-In-First-Out (LIFO) list of tasks. The agent only works on the task at the top of the stack.
- The **Source** of a task indicates who created it. 'internal' means it was generated by you for a strategic goal. 'player' means it was requested by a human player.

HOW TASK DECOMPOSITION WORKS:
When you provide a goal, an intelligent task decomposer will:
1. Analyze the current game state (health, food, inventory, equipment)
2. Check nearby resources (blocks, entities within range)
3. Review past experiences and lessons learned
4. Generate 3-12 concrete, achievable steps with clear end conditions
5. Filter out any continuous/never-ending tasks

Your `strategic_guidance` field is CRITICAL - it tells the decomposer HOW to approach the goal:
- Point out what went wrong with previous attempts
- Specify what resources to use or avoid
- Suggest alternative approaches or sequences
- Warn about specific pitfalls to avoid

CONTEXT FOR THE STUCK TASK:

1. OVERALL TASK STACK:
{stack_summary or 'Task stack is empty.'}

2. CURRENT TASK (Top of Stack):
- Source: {task_source}
{current_plan_text}

3. FAILED STEP (index {step_index + 1}):
{failed_step.get('description', 'Unknown')}

4. MID-LEVEL BRAIN'S REPORT:
- Reason for Failure: {reason or 'Not specified'}
- Reported Failures: {self._format_failure_list(failures)}
- Suggestion for a fix: {suggestion or 'None provided'}

5. RECENT SHORT-TERM MEMORY (last 50 events):
{recent_memory_text}

{('6. PLAYER CONTEXT (for player-sourced tasks):\n' + player_context) if player_context else ''}

YOUR DECISION:
Based on all the context, choose ONE of the following decisions and respond with a single JSON object.

POSSIBLE DECISIONS:
- **REVISE_AND_REPLACE** (internal tasks): Create a completely new goal to replace the current task. The decomposer will generate steps based on your guidance.
- **ADD_SUB_TASK** (all tasks): Create a prerequisite goal that must be completed first. Use this to solve a blocking issue.
- **DISCARD_TASK** (internal tasks): Give up on the current task entirely. The agent will move to the next task in the stack (if any).
- **REVISE_STEPS** (player tasks): Keep the same goal but have the decomposer regenerate steps with new strategic guidance that addresses the failure.
- **DISCARD_AND_REPORT** (player tasks): Give up on the player's task and inform them why.
- **REJECT_REQUEST** (all tasks): Do nothing. Use this if retrying the same approach is best or the mid-level's suggestion is flawed.

JSON RESPONSE FORMAT:
{{
  "decision": "CHOOSE_ONE_OF_THE_ABOVE",
  "explanation": "Your brief rationale for the decision.",
  "guidance": "Clear, actionable instructions for the mid-level executor.",
  "new_goal": "If using ADD_SUB_TASK or REVISE_AND_REPLACE, provide the new goal description here.",
  "strategic_guidance": "IMPORTANT: Provide specific guidance to the task decomposer about HOW to achieve this goal. Include what went wrong, what to try differently, what resources to use, etc.",
  "player_message": "If the player should be informed, what should the agent say?"
}}

EXAMPLES OF GOOD STRATEGIC GUIDANCE:
✓ "Previous attempt failed because we didn't have a crafting table. First ensure we have one before trying to craft tools."

EXAMPLES OF BAD STRATEGIC GUIDANCE (too vague):
✗ "Try again."
✗ "Be careful."
✗ "Do it better this time."

**CRITICAL**: Your strategic_guidance should be specific and actionable, pointing out exactly what the decomposer should consider when generating steps.

Rules:
- You must choose only ONE decision.
- For internal tasks, you may use: REVISE_AND_REPLACE, ADD_SUB_TASK, DISCARD_TASK, REJECT_REQUEST.
- For player tasks, you may use: REVISE_STEPS, ADD_SUB_TASK, DISCARD_AND_REPORT, REJECT_REQUEST.
- The response must be ONLY the JSON object.
"""

        try:
            decision_payload = await self.llm.send_request([], prompt)
        except Exception as exc:
            logger.error("Failed to obtain stuck-task decision from LLM: %s", exc)
            return {
                'decision': 'no_change',
                'explanation': 'LLM decision unavailable.',
                'guidance': suggestion or 'Retry with a slightly different approach.'
            }
        decision_data = self._parse_llm_json(decision_payload)

        decision = decision_data.get('decision', 'REJECT_REQUEST').upper()
        explanation = decision_data.get('explanation', '')
        guidance = decision_data.get('guidance', '')
        player_message = decision_data.get('player_message')
        new_goal = decision_data.get('new_goal', '')
        strategic_guidance = decision_data.get('strategic_guidance', '')

        result_decision = 'no_change'

        # Handle internal tasks
        if task_source == 'internal':
            if decision == 'REVISE_AND_REPLACE':
                goal_text = new_goal or active_task.get('goal')
                logger.info(f"Decomposing revised goal: {goal_text}")
                
                replacement = await self.task_planner.decompose_goal_to_steps(
                    goal=goal_text,
                    strategic_guidance=strategic_guidance or active_task.get('strategic_guidance', ''),
                    source=task_source,
                    player_name=player_name
                )
                
                if replacement:
                    await self.task_stack_manager.replace_active_task(replacement)
                    result_decision = 'updated_task'
                else:
                    logger.error(f"Failed to decompose revised goal: {goal_text}")
                    result_decision = 'no_change'

            elif decision == 'ADD_SUB_TASK':
                sub_goal = new_goal or f"Resolve prerequisite for: {failed_step.get('description', 'current step')}"
                logger.info(f"Decomposing sub-task goal: {sub_goal}")
                
                sub_task = await self.task_planner.decompose_goal_to_steps(
                    goal=sub_goal,
                    strategic_guidance=strategic_guidance,
                    source='internal',
                    player_name=player_name
                )
                
                if sub_task:
                    sub_task['parent_goal'] = active_task.get('goal')
                    await self.task_stack_manager.push_task_plan(sub_task)
                    result_decision = 'pushed_sub_task'
                else:
                    logger.error(f"Failed to decompose sub-task goal: {sub_goal}")
                    result_decision = 'no_change'

            elif decision == 'DISCARD_TASK':
                await self.task_stack_manager.discard_active_task(reason=explanation or guidance)
                result_decision = 'discarded_task'

        # Handle player tasks
        else:
            if decision == 'REVISE_STEPS':
                goal_text = active_task.get('goal')
                logger.info(f"Re-decomposing player task with new guidance: {goal_text}")
                
                revised_plan = await self.task_planner.decompose_goal_to_steps(
                    goal=goal_text,
                    strategic_guidance=strategic_guidance or 'Try a different approach to achieve this goal.',
                    source='player',
                    player_name=player_name
                )
                
                if revised_plan:
                    await self.task_stack_manager.replace_active_task(revised_plan)
                    result_decision = 'updated_task'
                else:
                    logger.error(f"Failed to re-decompose player task: {goal_text}")
                    result_decision = 'no_change'

            elif decision == 'DISCARD_AND_REPORT':
                await self.task_stack_manager.discard_active_task(reason=explanation or guidance)
                if not player_message:
                    player_message = f"Sorry {player_name}, I cannot complete '{active_task.get('goal', 'your request')}'."
                result_decision = 'discarded_task'

            elif decision == 'ADD_SUB_TASK':
                sub_goal = new_goal or f"Prerequisite for player request: {active_task.get('goal')}"
                logger.info(f"Decomposing sub-task for player request: {sub_goal}")
                
                sub_task = await self.task_planner.decompose_goal_to_steps(
                    goal=sub_goal,
                    strategic_guidance=strategic_guidance,
                    source='internal',
                    player_name=player_name
                )
                
                if sub_task:
                    sub_task['parent_goal'] = active_task.get('goal')
                    await self.task_stack_manager.push_task_plan(sub_task)
                    result_decision = 'pushed_sub_task'
                else:
                    logger.error(f"Failed to decompose sub-task: {sub_goal}")
                    result_decision = 'no_change'

        # Fallback guidance
        if not guidance:
            if result_decision == 'pushed_sub_task':
                guidance = 'Execute the newly added prerequisite task first.'
            elif result_decision == 'updated_task':
                guidance = 'Follow the updated task plan.'
            elif result_decision == 'discarded_task':
                guidance = 'Await further instructions from the high-level brain.'
            else:
                guidance = suggestion or 'Retry with a different approach.'

        return {
            'decision': result_decision,
            'explanation': explanation or guidance,
            'guidance': guidance,
            'player_message': player_message,
            'player_name': player_name,
            'task_source': task_source
        }

    async def handle_player_directive(self, request: Dict[str, Any]) -> Dict[str, Any]:
        """Handle new task directives originating from a player."""

        player_name = request.get('player_name') or 'Unknown'
        directive = request.get('directive') or request.get('suggestion') or ''
        if not directive:
            logger.warning("Player directive request missing directive text")
            return {
                'decision': 'reject_player_request',
                'explanation': 'No actionable directive provided.',
                'guidance': 'Politely ask the player to restate their request.'
            }

        stack_summary = self.task_stack_manager.generate_task_stack_summary()
        active_task = self.task_stack_manager.get_active_task()
        current_task_text = self.task_planner.format_task_plan_for_prompt(active_task)

        player_data = self.memory_manager.get_player_data(player_name) or {}
        relationship = player_data.get('relationship', 'neutral')
        trust_level = player_data.get('trust_level', 0.5)
        personality = ", ".join(player_data.get('personality', [])[-3:]) or 'unknown'
        preferences = ", ".join(player_data.get('preferences', [])[-3:]) or 'unknown'

        prompt = f"""
You are the high-level planner for a cooperative Minecraft agent.

Player "{player_name}" requested: "{directive}"

HOW TASK DECOMPOSITION WORKS:
When you accept a player's request and provide a goal, an intelligent task decomposer will:
1. Analyze the current game state (health, food, inventory, equipment)
2. Check nearby resources (blocks, entities within range)
3. Review past experiences and lessons learned
4. Generate 3-12 concrete, achievable steps automatically

Your `strategic_guidance` helps the decomposer understand HOW to achieve the goal:
- Specify preferred approaches or methods
- Point out available resources to use
- Warn about potential dangers or constraints
- Suggest the sequence or priority of actions

CURRENT CONTEXT:

Task stack status:
{stack_summary or 'Task stack is empty.'}

Currently active task:
{current_task_text}

Player relationship:
- Player: {player_name}
- Relationship status: {relationship}
- Trust level: {trust_level:.2f}
- Observed traits: {personality}
- Preferences: {preferences}

YOUR DECISION:
Decide whether to ACCEPT or REJECT this player directive: "{directive}"

Respond with JSON only:
{{
  "decision": "accept|reject",
  "reason": "brief rationale for your decision",
  "task_goal": "If accepting, provide a clear, specific goal description. Example: 'Gather 10 oak logs and deliver them to {player_name}'",
  "strategic_guidance": "If accepting, provide specific guidance for the task decomposer on HOW to achieve this goal. Include preferred methods, available resources, safety considerations, etc.",
  "player_message": "what to say to the player"
}}

EXAMPLES OF GOOD STRATEGIC GUIDANCE:
✓ "Prioritize safety - only work during daytime. Use the oak trees visible to the east."
✓ "We have a stone axe in inventory, use it to chop trees faster. Start with nearby birch forest."
✓ "Player prefers oak wood. Travel west to the oak forest, avoid the ravine to the north."

EXAMPLES OF BAD STRATEGIC GUIDANCE (too vague):
✗ "Just do it."
✗ "Be careful."
✗ (empty or missing)

Important:
- DO NOT provide steps in your response - the decomposer will generate them automatically
- Focus on whether the request is reasonable, safe, and aligns with current priorities
- Your strategic_guidance should give the decomposer context on HOW to approach the goal
- If you reject, provide a polite explanation for the player
"""

        try:
            decision_payload = await self.llm.send_request([], prompt)
        except Exception as exc:
            logger.error("Failed to evaluate player directive via LLM: %s", exc)
            fallback_message = (
                f"Sorry {player_name}, I cannot take on that request right now." if player_name else
                "Sorry, I cannot take on that request right now."
            )
            return {
                'decision': 'rejected_player_task',
                'explanation': 'LLM decision unavailable.',
                'guidance': 'Continue current priorities.',
                'player_message': fallback_message,
                'player_name': player_name
            }
        decision_data = self._parse_llm_json(decision_payload)

        decision = decision_data.get('decision', 'reject').lower()
        reason = decision_data.get('reason', '')
        player_message = decision_data.get('player_message')
        task_goal = decision_data.get('task_goal')
        strategic_guidance = decision_data.get('strategic_guidance', '')

        if decision == 'accept':
            goal_text = task_goal or f"Assist {player_name}: {directive}"
            
            # Always decompose the goal into steps
            logger.info(f"Decomposing accepted player directive: {goal_text}")
            task_plan = await self.task_planner.decompose_goal_to_steps(
                goal=goal_text,
                strategic_guidance=strategic_guidance,
                source='player',
                player_name=player_name
            )
            
            if task_plan:
                await self.task_stack_manager.push_task_plan(task_plan)
                logger.info("Accepted player directive from %s: %s", player_name, goal_text)
            else:
                logger.error("Failed to decompose player directive: %s", goal_text)
                return {
                    'decision': 'rejected_player_task',
                    'explanation': 'Failed to create task plan.',
                    'guidance': 'Continue with current priorities.',
                    'player_message': f"Sorry {player_name}, I couldn't figure out how to do that.",
                    'player_name': player_name
                }

            if not player_message:
                player_message = f"Okay {player_name}, I'll start working on '{goal_text}'."

            return {
                'decision': 'accepted_player_task',
                'explanation': reason or 'Accepted player directive.',
                'guidance': 'Begin executing the newly accepted player task.',
                'player_message': player_message,
                'player_name': player_name
            }

        # Reject path
        if not player_message:
            player_message = (
                f"Sorry {player_name}, I cannot take on that request right now. "
                "I will let you know when I'm available."
            )

        logger.info("Rejected player directive from %s: %s", player_name, directive)

        return {
            'decision': 'rejected_player_task',
            'explanation': reason or 'Rejected player directive.',
            'guidance': reason or 'Continue with current priorities.',
            'player_message': player_message,
            'player_name': player_name
        }

    def _extract_recent_memories_text(self, limit: int = 50) -> str:
        memories = self.memory_manager.get_recent_memories(limit)
        if not memories:
            return 'No recent memories.'

        lines = []
        for entry in memories:
            timestamp = entry.get('timestamp', '')
            event_type = entry.get('type', 'event')
            content = entry.get('content', '')
            lines.append(f"- [{timestamp}] {event_type}: {content}")
        return "\n".join(lines)

    def _format_failure_list(self, failures: list) -> str:
        if not failures:
            return 'No failure messages provided.'
        return "\n".join(f"- {failure}" for failure in failures[-5:])

    def _parse_llm_json(self, response: str) -> Dict[str, Any]:
        """Extract JSON payload from an LLM response."""
        if not response:
            return {}
        try:
            if '```json' in response:
                start = response.find('```json') + 7
                end = response.find('```', start)
                payload = response[start:end].strip()
            elif '```' in response:
                start = response.find('```') + 3
                end = response.find('```', start)
                payload = response[start:end].strip()
            else:
                start = response.find('{')
                end = response.rfind('}') + 1
                payload = response[start:end]
            return json.loads(payload)
        except Exception as exc:
            logger.error("Failed to parse LLM JSON response: %s", exc)
            logger.debug("LLM response: %s", response)
            return {}
